version: '3.4'

services:
  litecoin-node:
    build:
      context: .
    image: ghcr.io/xorde-labs/docker-litecoin-node:latest
    restart: unless-stopped
    stop_grace_period: 1m
    command: ${CMD_OPTS}
    volumes:
      - litecoin_data:/home/litecoin/.litecoin
    environment:
      - WALLET_ENABLE
      - WALLET_LEGACY
      - TESTNET_ENABLE
      - MAX_CONNECTIONS
      - RPC_ENABLE
      - RPC_USER
      - RPC_PASSWORD
      - RPC_ALLOW
      - RPC_PORT
      - RPC_BIND
      - CONFIG_FILE
      - SOCKS5_PROXY
      - TXINDEX_ENABLE
    ports:
      - ${RPC_PORT}:9332/tcp
      - ${PORT}:9333/tcp

volumes:
  litecoin_data:
    driver: local
